# -*- coding: utf-8 -*-
"""TelecomX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lRYuYkn9bSHnv3PHeWA877AMv_lHOItJ

## Imports
"""

import pandas as pd
import requests
import json
import numpy as np

"""# Extração"""

url = 'https://raw.githubusercontent.com/alura-cursos/challenge2-data-science/refs/heads/main/TelecomX_Data.json'

df = pd.read_json(url)

df.head()

"""# Transformação"""

response = requests.get(url)
data = response.json()
df = pd.json_normalize(data)

df.head()

df.info()

df['account.Charges.Total'].unique()

df['account.Charges.Total'] = pd.to_numeric(df['account.Charges.Total'], errors='coerce')
df['account.Charges.Total']

col_yes_no = ['Churn', 'customer.Partner', 'customer.Dependents', 'phone.PhoneService',
              'phone.MultipleLines', 'internet.OnlineSecurity', 'internet.OnlineBackup',
              'internet.DeviceProtection', 'internet.TechSupport', 'internet.StreamingTV',
              'internet.StreamingMovies', 'account.PaperlessBilling']
df[col_yes_no] = df[col_yes_no].apply(lambda x: x.replace('Yes', 1).replace('No', 0))
df[col_yes_no] = df[col_yes_no].astype(bool)

df.info()

df.isnull().sum()

df = df.dropna()
df.isnull().sum()

df['Contas_Diarias'] = df['account.Charges.Monthly'] / 30

df['Contas_Diarias']

df.head()

"""# Carga e Análise"""



"""# Relatório Final"""

